// Generated by CoffeeScript 1.9.3
var express, miki, router;

miki = require('../services/miki');

express = require('express');

router = express.Router();

router.route("/" + miki.config.apiVersions.v1 + "/schedule").get(function(req, res) {
  return res.json(miki.getSchedule());
});

module.exports = router;
