// Generated by CoffeeScript 1.9.1
module.exports = {
  getManageSchedule: function() {
    return console.log('getManageSchedule');
  },
  getListSchedule: function() {
    return console.log('getListSchedule');
  }
};
