// Generated by CoffeeScript 1.9.3
var FluxibleComponent, HtmlComponent, React, Router, api, app, config, debug, express, navigateAction, port, router, serialize, server, staticPath;

express = require('express');

api = require('./api');

React = require('react');

Router = require('react-router');

navigateAction = require('../actions/navigate');

app = require('./fluxibleApp');

serialize = require('serialize-javascript');

debug = require('debug')('Example');

config = require('../configs/configLoader');

FluxibleComponent = require('fluxible/addons/FluxibleComponent');

HtmlComponent = React.createFactory(require('../components/Html.jsx'));

require('node-jsx').install();

server = express();

staticPath = __dirname + "/../../build";

server.use('/build', express["static"](staticPath));

router = express.Router();

router.route('/list').get(function(req, res) {
  return res.json({
    mesage: "this is api/list"
  });
});

server.use('/api', router);

server.use(function(req, res, next) {
  var context;
  context = app.createContext();
  debug('Executing navigate action');
  Router.run(app.getComponent(), req.path, function(Handler, state) {
    context.executeAction(navigateAction, state, function() {
      var Component, exposed, html;
      debug('Exposing context state');
      exposed = 'window.App=' + serialize(app.dehydrate(context)) + ';';
      debug('Rendering Application component into html');
      Component = React.createFactory(Handler);
      html = React.renderToStaticMarkup(HtmlComponent({
        state: exposed,
        markup: React.renderToString(React.createElement(FluxibleComponent, {
          context: context.getComponentContext()
        }, Component()))
      }));
      debug('Sending markup');
      res.send(html);
    });
  });
});

port = process.env.PORT || 3434;

server.listen(port);

console.log('Listening on port ' + port);
