// Generated by CoffeeScript 1.9.1
var CSON, Kojima, Nishino, Okada, Tashima, config, meru, miki;

Nishino = require('./libs/miki');

Kojima = require('./libs/kojimako');

Okada = require('./libs/naachan');

Tashima = require('./libs/meru');

CSON = require('cson');

config = CSON.load('./tentoumu-chu.cson');

miki = new Nishino(config);

meru = new Tashima(miki);

meru.startMonitor();
