// Generated by CoffeeScript 1.8.0
({
  managePath: "schedule823sdwe.html",
  token: "12345",
  host: "127.0.0.1",
  port: 3434,
  redis_host: "192.168.59.103",
  redis_port: 6379,
  headless: "headless",
  scheduleKey: "schedule",
  douyuRoomAPI: "http://www.douyutv.com/api/client/room/",
  douyuAvatarAPI: "http://uc.douyutv.com/avatar.php",
  douyuWebPicUrl: "http://staticlive.douyutv.com/upload/web_pic",
  roomCheckInterval: 120000,
  roomInfo: [
    {
      disabled: false,
      room_id: 2246,
      room_alias: "akb48房间",
      always_show: true
    }, {
      disabled: false,
      room_id: 2319,
      room_alias: "ske48房间",
      always_show: true
    }, {
      disabled: false,
      room_id: 6186,
      room_alias: "hkt48房间",
      always_show: false
    }, {
      disabled: false,
      room_id: 3622,
      room_alias: "nmb48房间",
      always_show: false
    }, {
      disabled: false,
      room_id: 141261,
      room_alias: "sashi",
      always_show: true
    }, {
      disabled: false,
      room_id: 83376,
      room_alias: "mayuyu",
      always_show: true
    }, {
      disabled: false,
      room_id: 67299,
      room_alias: "yukirin",
      always_show: true
    }, {
      disabled: true,
      room_id: 129661,
      room_alias: "haruppi",
      always_show: true
    }
  ],
  scheduleFetchRssUrl: "http://feedblog.ameba.jp/rss/ameblo/akb48tvinfo/rss20.xml",
  scheduleTemplatesKey: "scheduleTemplates"
});
