// Generated by CoffeeScript 1.9.3
var CSON, Miki;

CSON = require('season');

Miki = (function() {
  function Miki() {
    this.assertConfig();
    this.ScheduleData = {};
  }

  Miki.prototype.updateRoomInfo = function(roomInfo) {};

  Miki.prototype.getRoomInfo = function() {};

  Miki.prototype.updateSchedule = function(schedule) {
    return this.ScheduleData = schedule;
  };

  Miki.prototype.getSchedule = function() {
    return this.ScheduleData;
  };

  Miki.prototype.assertConfig = function() {
    var base, base1, base10, base11, base12, base13, base14, base15, base2, base3, base4, base5, base6, base7, base8, base9;
    this.config = CSON.readFileSync(__dirname + "/../configs/tentoumu-chu.cson");
    if ((base = this.config).host == null) {
      base.host = '127.0.0.1';
    }
    if ((base1 = this.config).port == null) {
      base1.port = 3434;
    }
    if ((base2 = this.config).redis_host == null) {
      base2.redis_host = '127.0.0.1';
    }
    if ((base3 = this.config).redis_port == null) {
      base3.redis_port = 6379;
    }
    if ((base4 = this.config).douyuRoomAPI == null) {
      base4.douyuRoomAPI = "http://www.douyutv.com/api/client/room/";
    }
    if ((base5 = this.config).douyuAvatarAPI == null) {
      base5.douyuAvatarAPI = "http://uc.douyutv.com/avatar.php";
    }
    if ((base6 = this.config).douyuWebPicUrl == null) {
      base6.douyuWebPicUrl = "http://staticlive.douyutv.com/upload/web_pic";
    }
    if ((base7 = this.config).zhanqiRoomAPI == null) {
      base7.zhanqiRoomAPI = "http://www.zhanqi.tv/api/static/live.roomid/";
    }
    if ((base8 = this.config).zhanqiAvatarAPI == null) {
      base8.zhanqiAvatarAPI = "http://pic.cdn.zhanqi.tv/avatar";
    }
    if ((base9 = this.config).zhanqiWebPicUrl == null) {
      base9.zhanqiWebPicUrl = "http://dlpic.cdn.zhanqi.tv/live";
    }
    if ((base10 = this.config).roomCheckInterval == null) {
      base10.roomCheckInterval = 120000;
    }
    if ((base11 = this.config).scheduleFetchRssUrl == null) {
      base11.scheduleFetchRssUrl = "http://feedblog.ameba.jp/rss/ameblo/akb48tvinfo/rss20.xml";
    }
    if ((base12 = this.config).scheduleTemplatesKey == null) {
      base12.scheduleTemplatesKey = "scheduleTemplates";
    }
    if ((base13 = this.config).scheduleCheckInterval == null) {
      base13.scheduleCheckInterval = 120000;
    }
    if ((base14 = this.config).apiVersions == null) {
      base14.apiVersions = {
        'v1': 'v1'
      };
    }
    return (base15 = this.config).expireOffset != null ? base15.expireOffset : base15.expireOffset = 0;
  };

  return Miki;

})();

module.exports = new Miki();
