// Generated by CoffeeScript 1.9.3
var miki;

miki = require('../assistance/miki');

module.exports = {
  name: 'schedule',
  read: function(req, resource, params, config, callback) {
    var schedule;
    console.log("+try fetch schedule");
    console.log(callback);
    schedule = miki.getSchedule();
    return callback(null, schedule);
  },
  create: function(req, resource, params, body, config, callback) {
    console.log("+try create programme");
    console.log("params");
    console.log(params);
    console.log("body");
    console.log(body);
    console.log(callback);
    return callback(null, params);
  }
};
