// Generated by CoffeeScript 1.9.3
var ScheduleStore;

ScheduleStore = require('../stores/ScheduleStore');

module.exports = function(context, payload, done) {
  console.log("add programme");
  return context.service.create('schedule', payload, {}, function(err, schedule) {
    console.log("call api done try dispatch ADD_PROGRAME");
    context.dispatch('ADD_PROGRAME', schedule);
    return done();
  });
};
