// Generated by CoffeeScript 1.9.3
module.exports = function(context, payload, done) {
  return context.service.read('schedule', {}, {}, function(err, schedule) {
    console.log("fetch schedule done");
    context.dispatch('UPDATE_SCHEDULE', schedule);
    return done();
  });
};
