// Generated by CoffeeScript 1.9.3
var ScheduleStore;

ScheduleStore = require('../stores/ScheduleStore');

module.exports = function(context, payload, done) {
  console.log("try fetch in showSchedule");
  return context.service.read('schedule', {}, {}, function(err, schedule) {
    console.log("try dispatch");
    context.dispatch('UPDATE_SCHEDULE', schedule);
    return done();
  });
};
