// Generated by CoffeeScript 1.9.1
var CSON, config;

CSON = require('season');

console.log(__dirname);

config = CSON.readFileSync(__dirname + "/tentoumu-chu.cson");

module.exports = {
  port: 3434,
  apiVersion: {
    v1: 'v1'
  }
};
