// Generated by CoffeeScript 1.6.3
var generatePic, headlessUrl, phantom, redis, scheduleDirtyFlagKey;

phantom = require('phantom');

redis = require('redis').createClient();

scheduleDirtyFlagKey = 'schedule:isdirty';

headlessUrl = "http://127.0.0.1:3434/headless";

generatePic = function() {
  return redis.get(scheduleDirtyFlagKey, function(err, isdirty) {
    if (isdirty === "true") {
      return phantom.create(function(ph) {
        return ph.createPage(function(page) {
          return page.open(headlessUrl, function(status) {
            page.render('static_content/schedule.png');
            console.log("Output on " + new Date());
            return redis.set(scheduleDirtyFlagKey, false);
          });
        });
      });
    }
  });
};

setInterval(generatePic, 5000);
