// Generated by CoffeeScript 1.9.1
var ApplicationStore, createStore;

createStore = require('fluxible/addons').createStore;

ApplicationStore = createStore({
  storeName: 'ApplicationStore',
  handlers: {
    'CHANGE_ROUTE': 'handleNavigate'
  },
  initialize: function() {
    return this.currentRoute = null;
  },
  handleNavigate: function(route) {
    if (this.currentRoute && route.path === this.currentRoute.path) {
      return;
    }
    this.currentRoute = route;
    return this.emitChange();
  },
  getState: function() {
    return {
      route: this.currentRoute
    };
  },
  dehydrate: function() {
    return this.getState();
  },
  redydrate: function(state) {
    return this.currentRoute = state.route;
  }
});

module.exports = ApplicationStore;
