// Generated by CoffeeScript 1.9.3
var ScheduleStore, createStore;

createStore = require('fluxible/addons').createStore;

ScheduleStore = createStore({
  storeName: 'ScheduleStore',
  handlers: {
    'UPDATE_SCHEDULE': 'updateSchedule'
  },
  initialize: function() {
    return this.schedule = {};
  },
  getSchedule: function() {
    console.log("ScheduleStore: getSchedule()");
    return schedule;
  },
  updateSchedule: function(schedule) {
    console.log("ScheduleStore: updateSchedule()");
    return this.schedule = schedule;
  }
});

module.exports = ScheduleStore;
