// Generated by CoffeeScript 1.9.1
var FeedParser, Tashima, moment, request;

request = require('request');

moment = require('moment');

FeedParser = require('feedparser');

Tashima = (function() {
  function Tashima(miki1) {
    this.miki = miki1;
  }

  Tashima.prototype.startMonitor = function() {
    var checker, miki, url;
    miki = this.miki;
    url = miki.config.scheduleFetchRssUrl;
    checker = function() {
      var feedparser, getTopArticle, req;
      console.log("[meru] start checker");
      req = request(url);
      feedparser = new FeedParser();
      getTopArticle = function() {
        var article;
        article = this.read();
        feedparser.removeListener('readable', getTopArticle);
        miki.updateSchedule(article);
        console.log("[meru] feed loaded, schedule a new checker");
        return setTimeout(checker, miki.config.scheduleCheckInterval);
      };
      req.on('response', function(res) {
        if (res.statusCode !== 200) {
          return this.emit('error', new Error('Bad status code'));
        }
        return this.pipe(feedparser);
      });
      return feedparser.on('readable', getTopArticle);
    };
    return checker();
  };

  return Tashima;

})();

module.exports = Tashima;
