// Generated by CoffeeScript 1.8.0
var Bangumi, BangumiManager, Meru;

Bangumi = (function() {
  function Bangumi(startDate, timeStart, timeEnd, station, title, member) {
    this.startDate = startDate;
    this.timeStart = timeStart;
    this.timeEnd = timeEnd;
    this.station = station;
    this.title = title;
    this.member = member;
  }

  return Bangumi;

})();

BangumiManager = (function() {
  BangumiManager.bangumiList = [];

  function BangumiManager() {}

  BangumiManager.prototype.addOrUpdate = function(bangumi) {};

  BangumiManager.prototype.clearExpiredBangumi = function() {};

  return BangumiManager;

})();

Meru = (function() {
  function Meru(miki) {
    this.miki = miki;
  }

  Meru.prototype.startMonitor = function() {};

  return Meru;

})();
