// Generated by CoffeeScript 1.8.0
var Okada, Room, fs, moment, request, roomsData;

request = require('request');

fs = require('fs');

moment = require('moment');

roomsData = [];

Room = (function() {
  function Room(room_id, show_status, room_name, show_time, room_src, url, owner_uid, show_details, fans, always_show) {
    this.room_id = room_id;
    this.show_status = show_status;
    this.room_name = room_name;
    this.show_time = show_time;
    this.room_src = room_src;
    this.url = url;
    this.owner_uid = owner_uid;
    this.show_details = show_details;
    this.fans = fans;
    this.always_show = always_show;
  }

  Room.prototype.duration = function() {
    var timestamp;
    timestamp = parseInt(this.show_time);
    return moment.unix(timestamp).locale('zh-cn').fromNow(true);
  };

  return Room;

})();

Okada = (function() {
  function Okada(miki) {
    this.miki = miki;
  }

  Okada.prototype.startMonitor = function() {
    var checker, miki, r, room, url, _i, _len, _ref, _results;
    miki = this.miki;
    checker = function(room) {
      return request(room.url, function(err, res, body) {
        var e, obj;
        try {
          obj = JSON.parse(body).data;
          room.show_status = parseInt(obj.show_status);
          room.room_name = obj.room_name;
          room.show_time = obj.show_time;
          room.room_src = obj.room_src;
          room.owner_uid = obj.owner_uid;
          room.show_details = obj.show_details;
          room.fans = obj.fans;
          miki.updateRoom(room);
        } catch (_error) {
          e = _error;
          console.log(body);
          console.log("------------");
        }
        return setTimeout((function() {
          return function() {
            return checker(room);
          };
        })(), miki.config.roomCheckInterval);
      });
    };
    _ref = this.miki.config.roomInfo;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      r = _ref[_i];
      url = this.miki.config.douyuRoomAPI + r.room_id;
      room = new Room(r.room_id, 0, '', 0, '', url, '', '', 0, r.always_show);
      _results.push(checker(room));
    }
    return _results;
  };

  return Okada;

})();

module.exports = Okada;
