// Generated by CoffeeScript 1.9.3
var Tashima, meru, miki, server;

miki = require('./assistance/miki');

server = require('./server/server');

Tashima = require('./assistance/meru');

meru = new Tashima(miki);

meru.startService();

server.start();
