// Generated by CoffeeScript 1.9.3
var Tashima, meru, miki, server;

miki = require('./services/miki');

Tashima = require('./services/meru');

server = require('./server/server');

meru = new Tashima(miki);

meru.startService();

server.start();
