// Generated by CoffeeScript 1.9.3
var React, app, dehydratedState;

React = require('react');

app = require('../server/fluxibleApp');

dehydratedState = window.App;

window.React = React;

app.rehydrate(dehydratedState, function(err, context) {
  var mountNode;
  if (err) {
    throw err;
  }
  window.context = context;
  mountNode = document.getElementById('app');
  return React.render(context.createElement(), mountNode, function() {
    return console.log("react rendered");
  });
});
